### ISSUE TITLE
good first issue 

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Naruto-Shippuden#1]
You can see another character in the website link that I have given in the readme section. From there you can choose anyone.
I would love to see more new ones. It's okay if your favourite character is included and you still wish to contribute the same. But if that's not the case then please add new unique ones.

Happy Coding :)

**Comment by jigarvyasidea** [comment]
I am good at this kind of issue.

**Comment by yogesh2k21** [comment]
can i change page UI?

**Comment by AsmaIbrahimButt** [comment]
im good at this type issue

**Comment by Deepakv14** [comment]
> You can see another character in the website link that I have given in the readme section. From there you can choose anyone. I would love to see more new ones. It's okay if your favourite character is included and you still wish to contribute the same. But if that's not the case then please add new unique ones.
> 
> Happy Coding :)

I want to do this. Can u assign this to me?

**Comment by Deepakv14** [comment]
I want to do this. Can u assign this to me?

**Comment by KulkarniKrishna** [comment]
hey, this is an interesting repository for beginners which is I am. Please, give me a chance to pull my first request. Hence, requesting you to assign me this. Thanks.

**Comment by striver-80** [comment]
I will like to do this work. PLease assign it to me.

**Comment by CHAMP010** [comment]
Interested in improving the website!

**Comment by neerajmenon29** [comment]
i would like to contribute can u assign me

**Comment by kevinmody** [comment]
hey @vikhyatsingh123 i would love to contribute can you assign this to me please. Or can i just make a pr ?

**Comment by dchroninger** [comment]
I know this is old, but I've submitted a PR with some syntax corrections and reformatted index.html to make it easier to follow and read. Hopefully it's good enough to merge. lol
