### ISSUE TITLE
Code complexity

### ISSUE THREAD

**Issue by Aman-8955** [vikhyatsingh123/Naruto-Shippuden#1052]
I saw your website it's great but I want to say that it have very unreadable and long code. You should do like make a json file then fetch the all data from there. 
I already make the website like this on pokemon. 
Here is link:-
https://github.com/Aman-8955/Pokedex-app

Can i work to do it simple in your project. 
Please assign me this work. 
Thanks

**Comment by vikhyatsingh123** [comment]
Sure,
Make pr, I will merge it
