### ISSUE TITLE
Change the font in the cards

### ISSUE THREAD

**Issue by harshd008** [vikhyatsingh123/Naruto-Shippuden#1075]

**Comment by ssidharthsankar03** [comment]
plz assign me this issue

**Comment by rishuraj1708** [comment]
please assign this to me .

**Comment by mansi1309** [comment]
Hi @vikhyatsingh123 
I would to like to contribute to your repo.
can you please assign it to me .

**Comment by vikhyatsingh123** [comment]
@mansi1309 go ahead. no need to assign

**Comment by DXFURYMAN** [comment]
can you please assign this issue to me

**Comment by Pritee-gupta-jpg** [comment]
please assign this to me

**Comment by vikhyatsingh123** [comment]
I want to add naruto font in character name but not in description.
whoever completed it, create PR. I will merge it
