### ISSUE TITLE
Separate heroes and villians

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Naruto-Shippuden#1085]
It will be better if there is two separate tab for heroes and villains in the Naruto Anime

**Comment by code-with-ryan** [comment]
Hi, I would like to help with this. When you say 'two separate tabs' do you mean a a hero tab and a villain tab in the Navbar? Please let me know what you are looking for and I would be glad to assist!

**Comment by vikhyatsingh123** [comment]
not in navbar, you can add after accordian where "characters" is written. You can add two tab for heroes and villains or you can use switch button for that

**Comment by code-with-ryan** [comment]
Hi I am almost done with this. Just have to remember who is good or evil :)

If you see this before I send a PR, please assign me to this issue. Thanks!
