### ISSUE TITLE
Add some good background image/color in the website

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Naruto-Shippuden#1086]
It should be related to this anime.

**Comment by AdityaDhavale** [comment]
@vikhyatsingh123 I would like to work on this issue , will u please assign me?

**Comment by vikhyatsingh123** [comment]
@AdityaDhavale work on it.

**Comment by vikhyatsingh123** [comment]
Add screenshot of it too here

**Comment by AdityaDhavale** [comment]
@vikhyatsingh123 Sir u haven't assigned me .

**Comment by Shivangi015** [comment]
Hey @vikhyatsingh123 i am really interested in working on this issue. Please assign this to me.

**Comment by AdityaDhavale** [comment]
@vikhyatsingh123 Sir please assign me so that I can start working on the issue .

**Comment by vikhyatsingh123** [comment]
@AdityaDhavale work on it. Also share screenshot of the webpage. 
@Shivangi015 first come first serve. If aditya won't create pr in two days, I will assign to you

**Comment by AdityaDhavale** [comment]
![Screenshot (88)](https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/108582762/0f33c892-58ec-4ca4-bed9-ddf3e044602e)
@vikhyatsingh123 can u view the screenshot?  If yes is the background image fine ?

**Comment by AdityaDhavale** [comment]
@vikhyatsingh123 Sir please comment on the background image in the screenshot , so that I can create a PR.

**Comment by vikhyatsingh123** [comment]
@AdityaDhavale yeah, it's fine. Also correct the navbar of about page. it should look same as in home page

**Comment by ArchitSr313** [comment]
I want to work on this project please assign it to me when available

**Comment by Pritee-gupta-jpg** [comment]
please assign this to me
