### ISSUE TITLE
Modify the about page

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Naruto-Shippuden#1087]
Navbar is not proper, Box is not looking good. Improve overall page

**Comment by p-tirth** [comment]
Hey , I am a Front-End developer and I would like to work on this issue. Please could you assign it to me.

**Comment by vikhyatsingh123** [comment]
@p-tirth work on it

**Comment by Shivangi015** [comment]
Hey @vikhyatsingh123 can you please assign this task to me.

**Comment by p-tirth** [comment]
Hey @vikhyatsingh123 , I have made a PR 🚀. Eagerly waiting for you to look into it

**Comment by vikhyatsingh123** [comment]
@p-tirth it's already assigned to @Shivangi015

**Comment by p-tirth** [comment]
It was assigned to me first !
