### ISSUE TITLE
BUG : IN "Anko Mitarashi" SECTION THERE IS WRONG MARGIN OF IMAGE WHILE SCALE UP

### ISSUE THREAD

**Issue by amitdhiman5086** [vikhyatsingh123/Naruto-Shippuden#1089]
HOW TO SEE ISSUES:
1. GOTO WEBSITE 
2. REACHE THE "Anko Mitarashi " SECTION AND HOVER ON IMAGE
3. THE ISSUE IS INFRONT OF YOU 

THERE IS MISMATCHED  TOP HEIGHT  IN IMAGE .

I HAVE ALREADY  SOLVE IT PLEASE  ASSIGN IT TO ME.

THANK YOU.

**Comment by vikhyatsingh123** [comment]
ok
