### ISSUE TITLE
fix text color in dark mode

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Naruto-Shippuden#1107]
switch button text is not visible in dark mode. make it white

**Comment by Krrish2512** [comment]
Hey, just wanted to confirm if your repository is accepted in Hacktoberfest 2023 or not?

**Comment by vikhyatsingh123** [comment]
@Krrish2512 yes

**Comment by KeerthanaR29** [comment]
Please assign me to this issue @vikhyatsingh123

**Comment by Krrish2512** [comment]
> @Krrish2512 yes

I just created a PR to fix text color of the switch button in dark mode. But it shows that my PR in excluded from hacktoberfest in my hackoberfest profile. I'm doing this this for the first time. Can you help me why it this happening?

**Comment by vikhyatsingh123** [comment]
@Krrish2512 you have to create PR, I will merge it then after an hour, it will show in hacktoberfest

**Comment by Krrish2512** [comment]
Okay sir, have you assigned this issue to me or is there no need for the same?

**Comment by vikhyatsingh123** [comment]
no need to assign

**Comment by Krrish2512** [comment]
Hey, I just created a PR. Can you please tell me if it was successful or not?
