### ISSUE TITLE
The footers is overlapping 

### ISSUE THREAD

**Issue by git-create-devben** [vikhyatsingh123/Naruto-Shippuden#1116]
![image](https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/109157533/7978c303-8b0f-4a8b-9276-06876eaeb1b4)

It should be on a row not column.

**Comment by Albert-2** [comment]
hey @vikhyatsingh123
May i contribute to the issue under codepeak'23 if no one is still working on it .....
THANK YOU FOR CONSIDERING..... :)

**Comment by Albert-2** [comment]
can you please label the issue as a codepeak'23
Thank You....

**Comment by Albert-2** [comment]
hey @vikhyatsingh123 
i've submitted pr please review it
