### ISSUE TITLE
Some Images coming out of the Card

### ISSUE THREAD

**Issue by shrutimishra27** [vikhyatsingh123/Naruto-Shippuden#1118]
As seen below, some images are coming out of the card which is making overall card structure distorted.

Orignal:
<img width="957" alt="Screenshot 2023-10-19 201405" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/96042938/9a2094db-bbaf-4a96-8cec-78c1af1c37a5">
<img width="942" alt="Screenshot 2023-10-20 224049" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/96042938/5814a456-8c13-4e8f-8599-fb6b36b82b15">
<img width="957" alt="Screenshot 2023-10-20 222154" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/96042938/bd354232-29bc-4649-a0e8-76b68c045b22">

### Contributing under Hacktoberfest-23
Would like work on this issue.

**Comment by Krrish2512** [comment]
I would love to work on this one. Please assign me.

**Comment by shrutimishra27** [comment]
@vikhyatsingh123, with the issue creation, I have also created a PR for it that fixes all images flowing out of the card.
Please check. Thanks.
