### ISSUE TITLE
Search functionality not effective

### ISSUE THREAD

**Issue by Psalmuel01** [vikhyatsingh123/Naruto-Shippuden#1134]

**Comment by vikhyatsingh123** [comment]
work on it

**Comment by sigma390** [comment]
@vikhyatsingh123  can u explain what is needed in search function plz, i will solve it immediatly plz

**Comment by vikhyatsingh123** [comment]
@sigma390 wait if @Psalmuel01 will unable to do it. I will assign to you.

**Comment by Psalmuel01** [comment]
@vikhyatsingh123 you can let @sigma390 do it. i'm working on another issue you already assigned me.
@sigma390 , basically when you search, it should filter out the names as you're typing, for example if you search naruto and you've just writing nar, all names with nar in them should only be highlighted

**Comment by Mayank77maruti** [comment]
Hi @vikhyatsingh123 , please assign this task to me.

**Comment by vikhyatsingh123** [comment]
@Mayank77maruti go ahead

**Comment by Surajit0573** [comment]
Hi @vikhyatsingh123, it's still not done yet!!... I worked on a similar issue before. I can fix it in one day...Please assign it to me !!

**Comment by vikhyatsingh123** [comment]
@Surajit0573 do in both website

**Comment by Surajit0573** [comment]
@vikhyatsingh123 its already done. Close this issue as completed.
