### ISSUE TITLE
add google translator 

### ISSUE THREAD

**Issue by S-ishita** [vikhyatsingh123/Naruto-Shippuden#1140]
I want to add language translator in the website.

- User can translate the text into any language with just one click.
- user can select the preferred language from all the possible languages (100+ including hindi) available on Google after selecting a specific language, user will be able to :

       - again translate the page by choosing new language
       - showing the original language
       - turn off the translation for that site
Please assign this issue to me under hacktoberfest

**Comment by vikhyatsingh123** [comment]
ok sure
