### ISSUE TITLE
[BUG]: no navigation from contact page

### ISSUE THREAD

**Issue by S-ishita** [vikhyatsingh123/Naruto-Shippuden#1141]
There is no way to navigate to home page from contact page.I want to fix it.Please assign this issue to me under hacktoberfest

**Comment by S-ishita** [comment]
please assign this also @vikhyatsingh123 
I shall add a navbar or a home button which can redirect to homepage.

**Comment by S-ishita** [comment]
should i add navbar?

**Comment by vikhyatsingh123** [comment]
add navbar which should be same as in home
