### ISSUE TITLE
User Interface can be improved.

### ISSUE THREAD

**Issue by Harsh2504** [vikhyatsingh123/Naruto-Shippuden#1167]
I am participant from CodePeak

These are the improvements I can contribute to:
Home page:
1. Navbar styling.
2. Navbar responsiveness and proper adaption for various displays.
3. Improving color theme.
4. Improving card styling .
5. making layout more user friendly.

Improving website based on some proper theme rather than random styling given to any element.
And improve its dark mode to work respectively.

can i work on this ?
i am interested in solving more issues and making this website more enhanced I have lots of ideas , but let me finish this issue first.

**Comment by vikhyatsingh123** [comment]
ok, go ahead. I will give you points depending on your contribution

**Comment by Harsh2504** [comment]
> ok, go ahead. I will give you points depending on your contribution

thank you sir
Sir I am also working on your movie collection project will there be similar points criteria too. There also I have made issue for UI  improvements and creating new feature of "page showcasing specific movie info "

**Comment by vikhyatsingh123** [comment]
Yes, don't worry about points. 
if you want you can contribute to my other project too. That project needs some UI modification and many issues need to be fixed. It will count in Codepeak. 
https://github.com/vikhyatsingh123/SlugTerra
