### ISSUE TITLE
User interface improvement 2.0 (overall)

### ISSUE THREAD

**Issue by Harsh2504** [vikhyatsingh123/Naruto-Shippuden#1168]
I am participant from CodePeak

These are the improvements I can contribute to:
**Overall website:**
 1. Navbar styling.
 2. Navbar responsiveness and proper adaption for various displays.
 3. Improving color theme.
 4. Improving card styling .
 5. Layout of cards .
 6. making layout more user friendly.

**About Page:**
 1. can fix layout & styling
 2. Fix the navbar properly by adding all tabs .
 
**Contact Page:**
1. Can make Contact Form more attractive & improve its layout
2. Add Footer which is missing

**Improving website based on some proper theme rather than random styling given to any element.
And improve its dark mode to work respectively.**

**Extra:**
**1.Additionally** have some idea to make website look more attractive by adding some video visuals bt need to spend more time on it . 
**Video visuals :** adding a video section above navbar which will play video up to 30 sec at background continuously . this will add more attractive impact on anime users . and it looks to good .  **(video will be naruto edits and all)** either we can have different videos for different page or else same video for all pages. And above that **video in centre** we will have our **website title** or name.
**once you scroll down video will not be visible , and title bar will stick to the top of web page.**

it will look like this : (don't consider rest of UI in image just check video section)
![video player](https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/104843006/2c582e89-2ff6-4538-82eb-35278e8746ac)

https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/104843006/1c212183-193f-483d-9251-174f1b79dba0

2. Should **move contributors info to about tab** or **some other dedicated tab** making clean look.

can i work on this ?
if there are any suggestions plz tell me sir

**Comment by vikhyatsingh123** [comment]
@Harsh2504 you have created another issue for
```
Overall website:
Navbar styling.
Navbar responsiveness and proper adaption for various displays.
Improving color theme.
Improving card styling .
Layout of cards .
making layout more user friendly.
```
create a pr for that. Create 2 pr for about and contact page.

I liked your idea of implementing video. 

- Video should be after the navbar
- Keep video only on the homepage
- the video should be Naruto anime video
- replace carousel with your video

**Comment by vikhyatsingh123** [comment]
Also, a participant is working on data to fetch from api/single json file. So, you have to take pull after merging his pr

**Comment by Harsh2504** [comment]
> Also, a participant is working on data to fetch from api/single json file. So, you have to take pull after merging his pr

okay sir got it

**Comment by Harsh2504** [comment]
> erall website:
> Navbar styling.
> Navbar responsiveness and proper adaption for various displays.
> Improving color theme.
> Improving card styling .
> Layout of cards .
> making layout more user friendly.

okay so basically I will do three pr's 
1.home and overall UI
2.about 
3.contact

**Comment by vikhyatsingh123** [comment]
when will you create the pr

**Comment by Harsh2504** [comment]
> Also, a participant is working on data to fetch from api/single json file. So, you have to take pull after merging his pr

Did he completed that?
I was waiting for that so till then I was working on your Movies Collection projects UI 

I will work on Naruto project this Sunday .

**Comment by vikhyatsingh123** [comment]
No, he is working on multiple projects, also there is so many data to make object for that. He will complete it by 2 days
