### ISSUE TITLE
Select Language option is too odd on First Page

### ISSUE THREAD

**Issue by singhcoder694** [vikhyatsingh123/Naruto-Shippuden#1177]
Select Language can be made as per Website flow to make it look better.
<img width="944" alt="Screenshot 2023-12-17 103355" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/114601400/ba35d2e6-1a86-4377-a027-c412627bbbe1">

**Comment by vikhyatsingh123** [comment]
Yeah, I too think so. Fix it
