### ISSUE TITLE
Contact Page Pop Up on sending message.

### ISSUE THREAD

**Issue by singhcoder694** [vikhyatsingh123/Naruto-Shippuden#1178]
On contact page we can add popup on sending message to the team. Making the popup as showing error if message was not sent, otherwise showing it was successful.

**As of now it looks like this**
<img width="790" alt="Screenshot 2023-12-17 104315" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/114601400/fb66be29-b107-4097-a2cc-09fef1914626">

**Comment by vikhyatsingh123** [comment]
@singhcoder694 Ok fix it. Also, modify the form. Having invisible background color, it's hard to read the text
