### ISSUE TITLE
Search feature to find character.

### ISSUE THREAD

**Issue by nepalivai** [vikhyatsingh123/Naruto-Shippuden#1185]
Adding a search feature to find desired characters can be useful.
few design inspiration
![image](https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/108126089/452afcf2-6b44-44ff-8cba-8b35efce494b)

**Comment by vikhyatsingh123** [comment]
@nepalivai it's already there

**Comment by nepalivai** [comment]
Sorry for unclear instructions. It's can be quite confusing for the person looking at the site for the first time.
<img width="235" alt="image" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/108126089/e8c0622b-f952-44e5-adb7-f2487e6cdd99">
 So. I was suggesting to add it around here.
<img width="837" alt="image" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/108126089/f847d774-81f1-49d3-bbf5-5f83440c67ed">

**Comment by vikhyatsingh123** [comment]
@nepalivai leave it, I will check it later
