### ISSUE TITLE
Unable to see nav bar in contact page.

### ISSUE THREAD

**Issue by nepalivai** [vikhyatsingh123/Naruto-Shippuden#1186]
<img width="931" alt="image" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/108126089/225eaaaf-9001-4935-a5ce-3a8ebde048b2">

**Comment by vikhyatsingh123** [comment]
fix the background color of navbar

**Comment by nepalivai** [comment]
I think adding a bg-colour to nav bar would be nice and easy!! thoughts?
<img width="956" alt="image" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/108126089/a6832993-cdb7-4be1-a660-e0a05c56493e">
