### ISSUE TITLE
Shino's picture is not visible

### ISSUE THREAD

**Issue by Cgarg9** [vikhyatsingh123/Naruto-Shippuden#1190]
![image](https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/95637160/ee6784d4-0443-4062-b253-fcb4aa5495b2)
Shino's picture is not visible. Can i work on this under Codepeak'23

**Comment by halkotob** [comment]
I've edited the code and added a photo for Shino. Tested it locally, and the picture appears! I have a PR that should update and fix this. Please accept!

**Comment by vikhyatsingh123** [comment]
ok
