### ISSUE TITLE
[ENHANCEMENT] Add a back to top buttion for easier Navigation.

### ISSUE THREAD

**Issue by nepalivai** [vikhyatsingh123/Naruto-Shippuden#1193]
When you are at the end of the site it's hard to get back to the top. So, back to top button with smooth animation will be nice.

**Comment by vikhyatsingh123** [comment]
It was already there.
Actually there's a bug. In night mode, UI is fine but in light mode, there is two scroll happening as you can check it by scrolling down. Try to fix it.

**Comment by nepalivai** [comment]
@vikhyatsingh123 There is a script concerning the matter but I can't seem to find any div/button assigned to the script. I don't want to write unnecessary code to the file so if there is can you please tell me where it's located?
<img width="305" alt="image" src="https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/108126089/730bc004-12e5-4ae6-917d-8d0f3f2f42f0">

**Comment by vikhyatsingh123** [comment]
I think there is any div extra/missing. You can check once or leave it, I will look it later

**Comment by nepalivai** [comment]
Then I will create a new one you can find it later and remove it.

**Comment by vikhyatsingh123** [comment]
No, leave it
