### ISSUE TITLE
Adding Interactive Games Section to the Website

### ISSUE THREAD

**Issue by Surajit0573** [vikhyatsingh123/Naruto-Shippuden#1196]
This website is a popular place for fans to learn about their favourite characters. To make it more fun and keep people interested, I want to add a game section, where we can put some cool games all about Naruto characters. These games will help fans enjoy and learn more about the characters they love.

The games we can add in those sections are Guess the Character Game, Multiple-choice quizzes, Character Match-Up Games etc...

To start with, I want to create that section and add the most exciting game called "Guess the Character." This game will involve providing hints gradually, prompting users to guess the character correctly. Users will earn points for each level completed, with the highest scorers' names displayed on the website.

Contributing under : Codepeak 2023

**Comment by vikhyatsingh123** [comment]
I think it's a big task. You can add the game section. Do as much as you can. I will keep adding on later

**Comment by vikhyatsingh123** [comment]
If you want to work on this issue after codepeak, you can work on it

**Comment by Surajit0573** [comment]
working on it
