### ISSUE TITLE
Select language tab and playpause button coinciding 

### ISSUE THREAD

**Issue by harshendram** [vikhyatsingh123/Naruto-Shippuden#1214]
The select language button and play/pause button is overlapping each other making select language as unselectable .
![narutopullreq](https://github.com/user-attachments/assets/750d84c3-d415-412e-8d6c-842786f441c3)

**Comment by harshendram** [comment]
please assign this issue to me as a part of hacktoberfest2024 .I can fix this @vikhyatsingh123

**Comment by vikhyatsingh123** [comment]
@harshendram go ahead
