### ISSUE TITLE
Image of Hayate Gekko is not showing

### ISSUE THREAD

**Issue by Ayush-kr-giga** [vikhyatsingh123/Naruto-Shippuden#1222]
![Screenshot 2024-10-18 at 6 33 44 PM](https://github.com/user-attachments/assets/f8135f25-0a39-4497-8891-6fa4d7fe1d98)

we should fix this issue as it looks unappealing, and i can do it.

**Comment by Ankitgkp** [comment]
Done

**Comment by Ayush-kr-giga** [comment]
bro i have submitted pull request 2 days ago. @vikhyatsingh123  please check it
