### ISSUE TITLE
Fix wrong alt information on images

### ISSUE THREAD

**Issue by Evavic44** [vikhyatsingh123/Naruto-Shippuden#136]
Some characters have mismatched `alt=""` title. 

# For example: 

![Naruto_alt_issue](https://user-images.githubusercontent.com/62628408/135728063-7d7492b5-925a-494d-80de-1f9ecc19c5f8.png)

# Requested changes
Add correct `alt=""` title. 

Will love to work on this if approved.

**Comment by vikhyatsingh123** [comment]
not required. You can work on another issue.
