### ISSUE TITLE
Beautify

### ISSUE THREAD

**Issue by AbhinandanGautam** [vikhyatsingh123/Naruto-Shippuden#137]
I want to beautify this web page
1. Add some indentation to code
2. make look clean and beautiful

**Comment by AbhinandanGautam** [comment]
please assign me this I am new to opensource and want to contribute

**Comment by AbhinandanGautam** [comment]
Add hacktoberfest2021 label

**Comment by WajihaFatim** [comment]
may I know what we have to beautify

**Comment by vikhyatsingh123** [comment]
nothing
