### ISSUE TITLE
Add more characters in the list

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Naruto-Shippuden#2]
You can see another character in the website link that I have given in the readme section. From there you can choose anyone.
Before contributing, I request you to visit the website once to see the characters that are already there. I would love to see more new ones. It's okay if your favorite character is included and you still wish to contribute the same. But if that's not the case then please add new unique ones.

***Add some new Villains which are not added there. You can search from the search bar of the website that that card is added or not.***

Thank You!

**Comment by JanviRaina** [comment]
I would like to add more characters in this.

**Comment by vikhyatsingh123** [comment]
It's open for everyone. You can add it

**Comment by nekonako** [comment]
hi @vikhyatsingh123, i have make pull request to add more character

**Comment by PrajjwalPathak** [comment]
Hi @vikhyatsingh123, I would like to add a new character.
If you don't mind, can you please change the label from "hactoberfest" to "hacktoberfest".
I made the same mistake last year :)

**Comment by agaveyonatan** [comment]
Hi @vikhyatsingh123 i would love to contribute to this project!

**Comment by IshitaSingh23** [comment]
hey @vikhyatsingh123  I would like to contribute in this project and add more characters to the website !

**Comment by HiruniPerera** [comment]
Hi @vikhyatsingh123 I would love to contribute to your project and add more characters to your website!

**Comment by singlapriyanka315** [comment]
hi i would like to add more characters.

**Comment by techyAdi1** [comment]
Hi @vikhyatsingh123 I added Zabuza Momochi character in the index.html please accept my pr

**Comment by Soham2020** [comment]
### Hi @vikhyatsingh123 
Plz review my PR.
My PR number is #57 .

**Comment by raktim00** [comment]
Hello @vikhyatsingh123, Please add my PR #58

**Comment by biplab25** [comment]
Hi I would like to add more characters in this.

**Comment by biplab25** [comment]
hello @vikhyatsingh123  
Plz review my PR.
My PR number is #87  .

**Comment by prwankhade16** [comment]
Hi @vikhyatsingh123  please review my PR. My PR number is #55

**Comment by priyaastha** [comment]
Hello, @vikhyatsingh123 sir Please review and merge my PR. My PR number is #165 . Thank you.

**Comment by ashana1647** [comment]
Hi @vikhyatsingh123  please review and merge my PR. My PR number is #166 . Thank you

**Comment by prashant16oct** [comment]
Hi @vikhyatsingh123, i have solved some issue related to cards and navbar button. Please review my PR and merge it ( #173 ). Thank you

**Comment by Gourav-s12** [comment]
hello, @vikhyatsingh123  , i have added ebizo , a new character . 
please review and add PR #178 
and thank you for such a easy issue for beginner (i joined open contribution today )

**Comment by iamartyaa** [comment]
Hye @vikhyatsingh123 , I would like to work on this issue.

**Comment by KulkarniKrishna** [comment]
Hey there! I am very interested in this topic I would love to contribute to this issue. Kindly give me chance. Thanks.

**Comment by adityakumarsinha03** [comment]
Hello @vikhyatsingh123  Please review and merge my PR. My PR number is #205  . Thank you.

**Comment by striver-80** [comment]
Hello @vikhyatsingh123 please review and merge my PR. PR number #212 . Thanking you.

**Comment by Yash-RajSingh** [comment]
I can this issue. Please assign it to me

**Comment by Yuktashettigar16** [comment]
Hey @vikhyatsingh123 , I would like to work on this issue. Please assign

**Comment by agraghav26** [comment]
HI @vikhyatsingh123 !
I have added Might Guy, A new character.
Please review and add my PR #297
Regards

**Comment by Khushboo288** [comment]
I would Like to work on this as I am interested to contribute in this. Plz assign it to me.

**Comment by Khushboo288** [comment]
Hey, @vikhyatsingh123  I have added a new card, it is a unique which was not there before. 
So plz review and Merge my PR #346

**Comment by sadathshariff** [comment]
Hi @vikhyatsingh123 Would like to contribute to this can you assign me this issue

**Comment by vikhyatsingh123** [comment]
@TechnoFuge That card is already present there. Add new one

**Comment by TechnoFuge** [comment]
Hi, @vikhyatsingh123 I have added a new card Sound Four PR #440 which is a villain. Consider it for hacktoberfest.

**Comment by SLICKjp** [comment]
hey @vikhyatsingh123, I have added a new character card. Please merge my PR. #605. Thank you..

**Comment by SrikarGidugu** [comment]
Hey @vikhyatsingh123 , I have added the character card of Isaribi. Please review it. PR #615

**Comment by srimanpravardhan** [comment]
hey @vikhyatsingh123, I have added a new character card of kimimaro. Please merge my PR. #614 . Thank you..

**Comment by mciruzzi1** [comment]
Hey! I would love to add some characters if possible :D

**Comment by awgarri** [comment]
Hi! I would love to add some new characters to the page!

**Comment by shagen9285** [comment]
Hi, I made some Pull Requests with some new characters for the site :)

**Comment by shagen9285** [comment]
@vikhyatsingh123 I fixed the merge issue with the Gamatatsu pull request
