### ISSUE TITLE
Character is not in proper way after Shino Aburame

### ISSUE THREAD

**Issue by aayusranjan** [vikhyatsingh123/Naruto-Shippuden#270]
can you assign me I wanna to fix it

**Comment by vikhyatsingh123** [comment]
ok, do it

**Comment by vikhyatsingh123** [comment]
Also , add all the missing images there or maybe broken links

**Comment by aayusranjan** [comment]
Done pls check pr #284

**Comment by aayusranjan** [comment]
There is repeated character if you want to fix it up, I can do that to

**Comment by vikhyatsingh123** [comment]
OK, but I want to do that at last.
