### ISSUE TITLE
Overlaying Button

### ISSUE THREAD

**Issue by Mannuel25** [vikhyatsingh123/Naruto-Shippuden#370]
![IMG_20211010_004157](https://user-images.githubusercontent.com/68563757/136676494-f7d2a333-38ac-4618-a313-3d3d42e8c1ed.jpg)
![IMG_20211010_004133](https://user-images.githubusercontent.com/68563757/136676492-ab29c8ce-7d36-47b1-8c02-57a7bf9db20f.jpg)

These buttons aren't well placed.. I'd like to fix this.

Kindly assign this to me. Thanks

**Comment by B0s0** [comment]
This issue is fixed by  #372
