### ISSUE TITLE
[style][bug]Fix the overlapping div layers

### ISSUE THREAD

**Issue by B0s0** [vikhyatsingh123/Naruto-Shippuden#378]
Overlapping div has made this not so good looking change in the website. As you can see an extra layer of whitish background behind the cards.

![image](https://user-images.githubusercontent.com/80257174/136685262-68decc34-27a7-4204-91c7-13cdf77bcab9.png)

Actually, it should look like this, clean and amazing.

![image](https://user-images.githubusercontent.com/80257174/136685299-170e4c3a-5d38-449e-8886-c2e4db33df42.png)

# I can fix this issue, so please assign it to me. 😃 @vikhyatsingh123

**Comment by B0s0** [comment]
This issue can be fixed by #385

**Comment by amirvincent64** [comment]
related to #243
