### ISSUE TITLE
Adjust the back to top Button above the last card 

### ISSUE THREAD

**Issue by ampsteric** [vikhyatsingh123/Naruto-Shippuden#668]
The back-to-top button at the bottom of the page gets hidden under the cards, hence it should always be at the top of all the cards for a better user experience.

Please assign this issue to me as a part of hacktoberfest.

**Comment by georgioupanayiotis** [comment]
@ampsteric  can you please assign this to me?

**Comment by vikhyatsingh123** [comment]
Wait for 1 oct

**Comment by ampsteric** [comment]
@georgioupanayiotis I am not the owner of the repository , I have raised an issue so that I can be assigned to it and start working.

@vikhyatsingh123 yeah sure.

**Comment by ampsteric** [comment]
@vikhyatsingh123 it would be very helpful if you can please review it as soon as possible and merge it or label it as "hacktoberfest-accepted"

**Comment by vikhyatsingh123** [comment]
Ok, do it
