### ISSUE TITLE
whitespace in the right and low res landing page images

### ISSUE THREAD

**Issue by Welf06** [vikhyatsingh123/Naruto-Shippuden#678]
![image](https://user-images.githubusercontent.com/85446331/193398045-848d21ed-6b4c-4050-9941-a6bfff568d92.png)
I am willing to fix these 2 things, please assign it to me

**Comment by Mahekjain2706** [comment]
Hey, I want to solve this issue, can you assign it to me?

**Comment by darshikaguptaa** [comment]
Hey @vikhyatsingh123 , I want to work on this. Please assign this issue to me.

**Comment by Adityasaini10012001** [comment]
Hey @vikhyatsingh123 can you please assign this to me.
