### ISSUE TITLE
update Readme for Hacktober 2022

### ISSUE THREAD

**Issue by Shubhcs01** [vikhyatsingh123/Naruto-Shippuden#687]
Currently Readme is showing Hacktober 2021 image and description.

**Comment by Natan7** [comment]
And add label hacktoberfest-accepted

**Comment by moksh2212** [comment]
can i go for this?

**Comment by Shubhcs01** [comment]
> And add label hacktoberfest-accepted

I don't have access permission to create hacktoberfest-accepted label🤔
