### ISSUE TITLE
Screen is not fully adjusted as we scroll aside 

### ISSUE THREAD

**Issue by ARYAN-CODES-STAR** [vikhyatsingh123/Naruto-Shippuden#692]
i am talking about that orange portion in next comment

**Comment by ARYAN-CODES-STAR** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/78686630/193420406-b1db5347-1ab5-4a79-8a92-eb1e6ea2ba13.png)

**Comment by darshikaguptaa** [comment]
Hey, I'm interested in working on the issue. Please assign it to me.

**Comment by ARYAN-CODES-STAR** [comment]
I am actually interested and that's why I created this issue.

**Comment by vikhyatsingh123** [comment]
I Will assign you

**Comment by vikhyatsingh123** [comment]
Fork it and create PR.
