### ISSUE TITLE
Alignment of Image and text properly

### ISSUE THREAD

**Issue by ARYAN-CODES-STAR** [vikhyatsingh123/Naruto-Shippuden#694]
I want to work on image and text alignment for Hactober'22

**Comment by saiwali** [comment]
Hey @ARYAN-CODES-STAR  I would like work on this issue. I can make the images look better actually

**Comment by Harsh8084** [comment]
Hi @vikhyatsingh123 please assign this issue to me. I organise the image and text part  so that the website will look attractive.

**Comment by yosaami** [comment]
Hey, @vikhyatsingh123, please assign this project on image and text alignment.

**Comment by vikhyatsingh123** [comment]
@ARYAN-CODES-STAR do it
