### ISSUE TITLE
click to top (button) issues

### ISSUE THREAD

**Issue by shreyashkr17** [vikhyatsingh123/Naruto-Shippuden#702]
![image](https://user-images.githubusercontent.com/97216718/193458842-64233345-62e8-4972-b1bd-1a61a0ec60eb.png)

**Comment by shreyashkr17** [comment]
this button is out of windows size page

**Comment by ampsteric** [comment]
I have already fixed it in my recent PR

**Comment by shreyashkr17** [comment]
okay.

**Comment by vikhyatsingh123** [comment]
@shreyashkr17 it's still not fixed. So, do that one

**Comment by shreyashkr17** [comment]
Okay sir i will do it.
