### ISSUE TITLE
Want to modify navigation tabs and about section

### ISSUE THREAD

**Issue by vedsom** [vikhyatsingh123/Naruto-Shippuden#708]
Hey, @vikhyatsingh123 I want to improve your navigation tabs by reducing excess space, beautiful hover effect, and giving additional contribution by writing a good about section for your repository. So kindly assign me this issue under hacktoberfest 22

**Comment by Olaf51** [comment]
hey, i want to improve your navigation tabs, please assign it to me.

**Comment by Adityasaini10012001** [comment]
Hey , please assign this to me

**Comment by Hanuvesh** [comment]
hey , i am newbie in open source please assign me this

**Comment by vikhyatsingh123** [comment]
@vedsom created an issue so he will be assigned for this issue first.

**Comment by vedsom** [comment]
> @vedsom created an issue so he will be assigned for this issue first.
Thanku @vikhyatsingh123 . Could you please attach hacktoberfest tag so that it can be counted.
