### ISSUE TITLE
Redesign cards

### ISSUE THREAD

**Issue by Sanjanabharadwaj25** [vikhyatsingh123/Naruto-Shippuden#709]
The cards can have information that is shown to the user when the user hovers over the card.
I would like to work on this issue under hacktober fest 2022.

**Comment by vikhyatsingh123** [comment]
Sure, do it and attach screenshots or gif too

**Comment by hamzailyas237** [comment]
Can I work on this issue ?

**Comment by vikhyatsingh123** [comment]
@hamzailyas237 Sure. Also attach screenshots too
