### ISSUE TITLE
navigation links and button styling

### ISSUE THREAD

**Issue by Priyanshup891** [vikhyatsingh123/Naruto-Shippuden#736]

**Comment by Nikhil170404** [comment]
I want to work on image and text alignment for Hactober'22

**Comment by Nikhil170404** [comment]
I want to work on navigation links and button styling for Hactober'22

**Comment by Nanncyy** [comment]
I am also looking forward to contribute in projects for Hactober'22

**Comment by vikhyatsingh123** [comment]
attach screenshots with pr

**Comment by harshneolia** [comment]
Assign this to me Sir....I can Do it
