### ISSUE TITLE
Add smooth scroll 

### ISSUE THREAD

**Issue by AndrickSilva** [vikhyatsingh123/Naruto-Shippuden#758]
Hi Vikhyat, Can I please add smooth scroll to your website on back to top button. 
Thank You

**Comment by Chaim-007** [comment]
HI Vikhyat, It is with great pleasure I want to contribute to your code to add smooth scroll in your website. It will be highly grateful if I can get your permission to add it.
Thank you!

**Comment by shivjha-2712** [comment]
This has been done so could you please close this and merge my pull request as well #838
