### ISSUE TITLE
Add style to Dark mode button

### ISSUE THREAD

**Issue by AndrickSilva** [vikhyatsingh123/Naruto-Shippuden#759]
Also can I add style to the dark mode button

**Comment by AyonChowdhury1307** [comment]
Hey vikhyat singh please assign me i can add style to Dark mode button .

**Comment by RAJEEVKUMAR9598** [comment]
please sir give me this task..

**Comment by KinGVipEr01** [comment]
Hi sir! newbie to this fest and want to go with this project. 
Thankyou !

**Comment by vikhyatsingh123** [comment]
you all can give a try

**Comment by Neerajbhatia007** [comment]
Hi, 
added a toggle instead of dark mode button allow this task to me @vikhyatsingh123

**Comment by AndrickSilva** [comment]
Hi @vikhyatsingh123 i have fixed the smooth scroll and dark mode button and opened pr
Hope you like it.
Thankyou 😄

**Comment by itsaman123** [comment]
hey @vikhyatsingh123 please assign me this issue
