### ISSUE TITLE
Text is going out of the box

### ISSUE THREAD

**Issue by Purvesh77** [vikhyatsingh123/Naruto-Shippuden#781]
![Screenshot (6)](https://user-images.githubusercontent.com/107318324/194725766-3b6db402-dd05-4a2b-b9aa-9ae8b776efaa.png)

**Comment by Purvesh77** [comment]
@test999 @vctc @c99SRS @Natan7 I will work on this issue
Can anybody assign me this task ?

**Comment by abhishekbisht-1** [comment]
Please assign me this task I will do it for sure

**Comment by Neerajbhatia007** [comment]
Hi,
I have done this task please assign it to me so that I can push my changes @Purvesh77 @vikhyatsingh123
