### ISSUE TITLE
ADD  RESPONSIVE FOOTER TO THE WEBPAGE

### ISSUE THREAD

**Issue by rajatrai30** [vikhyatsingh123/Naruto-Shippuden#791]
Heyy @vikhyatsingh123 
I can add footer to this application.
I want to you to assign me with this issue raised.

**Comment by CoderDebjeet** [comment]
Heyy @vikhyatsingh123
I can add footer to this application.
I want to you to assign me with this issue raised.

**Comment by anirudh270** [comment]
Hey @vikhyatsingh123 , I would like to contribute to ur application.

**Comment by abhishekbisht-1** [comment]
i have solved the issue please accept my pull request. This is the link of screenshots of my work. Hope you like it.
https://drive.google.com/drive/folders/1sr3SL6L7YINAYyDdBnY0ZUI07RccF7kO

**Comment by Sejal-shh** [comment]
Hey @vikhyatsingh123 , I have solved this issue of adding responsive footer to the webpage.
Kindly assign me with the issue raised.

**Comment by vikhyatsingh123** [comment]
@abhishekbisht-1 drive folder is not shareable

**Comment by Viren0602** [comment]
Hello sir , can you assign this issue to me?
