### ISSUE TITLE
Updating About Page Section

### ISSUE THREAD

**Issue by harshvardhan614** [vikhyatsingh123/Naruto-Shippuden#810]
Hi @vikhyatsingh123 pls assign this issue to me

**Comment by animesh045** [comment]
Hi @vikhyatsingh123 pls assign this issue to me

**Comment by harshvardhan614** [comment]
Hi @vikhyatsingh123, merge my PR #846

**Comment by ogooluwanick** [comment]
Hello, has this issue been resolved?
