### ISSUE TITLE
Updating About PAge HEader and footer

### ISSUE THREAD

**Issue by harshvardhan614** [vikhyatsingh123/Naruto-Shippuden#811]
hey @vikhyatsingh123 pls assign this issue to me

**Comment by SantoshAnand271** [comment]
Hello sir can you assign this issue to me

**Comment by And-Rahul** [comment]
I have pretty good experience in this field. Can you assign me this issue?

**Comment by Viren0602** [comment]
Hello sir , can you assign this issue to me?

**Comment by rrrs07** [comment]
@vikhyatsingh123 bro please assign this issue to me
