### ISSUE TITLE
Card UI is not positioned  well 

### ISSUE THREAD

**Issue by psantosh16** [vikhyatsingh123/Naruto-Shippuden#820]
Hey,
@vikhyatsingh123 
Assign this issue to me and I will start to contribute  to it asap.
Thank You.

## Problem :- 

1. Individual Character cards are not positioned and this makes UI as well as UX bit wrong. And cause bad impression on user.
2. Some Images are not rendering properly.

![Screenshot 2022-10-11 at 10 36 13 PM](https://user-images.githubusercontent.com/99491679/195157903-f1b124e4-0001-4768-8f14-0e5874a3c6bc.png)
![Screenshot 2022-10-11 at 10 36 04 PM](https://user-images.githubusercontent.com/99491679/195157930-e4f4ce62-fc6d-48d5-a90a-7c7d3ce979b8.png)

## Solution :- 

1. Positioning cards well and making it responsive as well 
2. Fixing Image issue

**Comment by psantosh16** [comment]
Successfully resolved this issue  , please take look at this MR/PR request and approve it with hacktoberfest & hacktoberfest-accepted label . 

PR -> Fixed Image issue and improved UI of website #821

Thank You ,
@vikhyatsingh123

**Comment by And-Rahul** [comment]
I have pretty good experience in this field. Can you assign me this issue?
