### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by KeyurChanchad** [vikhyatsingh123/Naruto-Shippuden#84]
i can not send pull request

**Comment by vikhyatsingh123** [comment]
Just fork it and then add new card then send pull request

**Comment by HarshitShukla01** [comment]
> Just fork it and then add new card then send pull request

please merge my pull request that i recently  added of card of gamabunta before anyone else pull request otherwise it will again cause conflicts if you accepts someone other than mine.
