### ISSUE TITLE
Improving the frontend of home page

### ISSUE THREAD

**Issue by animesh045** [vikhyatsingh123/Naruto-Shippuden#840]
Hi @vikhyatsingh123 I've found somechanges in appearance of home page like there could be 3 cards rather than 2 and last 2 cards are misplaced + missing pics. 3rd card is kind of looking very strange. 

I'll try give my best to it.
Please assign this issue to me.

**Thank you 
Animesh**

**Comment by Rohans-7** [comment]
Hey @vikhyatsingh123 Can you assign this issue to me. It would be really for me as a beginner. I have worked on some projects in my college I can use that knowledge here. 
Please assign this issue to me.
Thank you.

**Comment by shradham2612** [comment]
Hey @vikhyatsingh123  
I have worked  on some frontend designing projects and I think that I will be able to add some cool effects to this project
please assign me this task
