### ISSUE TITLE
Change the readme section where code template is written to the updated one

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/Naruto-Shippuden#864]
you can take help from the code present for the website

**Comment by Satyabrat-Ojha** [comment]
@vikhyatsingh123 I got the task, can you please assign it to me

**Comment by Satyabrat-Ojha** [comment]
@vikhyatsingh123 please check it out

**Comment by Nilesh179** [comment]
Hey, I want to try make a pull request as I don't really know exactly how it's done so can you please assign this task to me.
