### ISSUE TITLE
Wrong Image for Anko Mitarashi

### ISSUE THREAD

**Issue by MashyBasker** [vikhyatsingh123/Naruto-Shippuden#893]
The thumbnail image for Anko Mitarashi in the website is of Minato Namikaze.

**Comment by IamAshrafSyed** [comment]
kindly pls assign it to me already did the changes above

**Comment by MashyBasker** [comment]
Hi @IamAshrafSyed I've already worked on the aforementioned issue. You can contact the maintainer for the issue #898 and #899

**Comment by IamAshrafSyed** [comment]
Sure will tq
