### ISSUE TITLE
Image not rendering for Yamato

### ISSUE THREAD

**Issue by priyanshi-git** [vikhyatsingh123/Naruto-Shippuden#903]
Can I work on this issue and add another picture for yamato ?

![image](https://user-images.githubusercontent.com/82112540/196610133-7c35397b-bbcf-4a7b-9b0e-0966f28c446c.png)

**Comment by Kokonodray2001** [comment]
can i do this ?

**Comment by Kokonodray2001** [comment]
plzz assign this to me

**Comment by vikhyatsingh123** [comment]
add other image links too
