### ISSUE TITLE
Contact Us page missing

### ISSUE THREAD

**Issue by phoniex1629** [vikhyatsingh123/Naruto-Shippuden#936]
I can create a contact us page, with the information of username, email, phone no, message and a send option.

I have already created a contact us page before so I can do it.

Please assign me this under HactoberFest2022 tag.

**Comment by Brainskull24** [comment]
Can you pls assign this issue to me @vikhyatsingh123 ?

**Comment by rrrs07** [comment]
could please assign me this issue @vikhyatsingh123

**Comment by SAURABHTIWARIVBSPU** [comment]
<!DOCTYPE html>
<html>
<head>
<title>Future</title>
<link rel="stylesheet" href="css/style.css">
<style>
body{font-family:arial;
}
table, th, td {
   
	height:80px;
}
table, th, td, img
{
text-align:center;
}



</style>
</head>
<body bgcolor="yellow">


</table>
<table  align=center>

<tr>
<td colspan="6"  class="head2"><h2>Contact Us</h2>
<label>Your Name</label>
<input type="text" class="btn"><br>
<label>Your Email</label>&nbsp  
<input type="text" class="btn"><br>
<label>Your Phone</label>
<input type="text" class="btn"><br>
<label>Subject</label>&nbsp &nbsp &nbsp &nbsp 
<input type="text" class="btn"><br>
<label>Message</label>&nbsp &nbsp &nbsp
<textarea rows="10" style="width:700px;"></textarea><br>
<input type="submit" value="Send Now" class="btn2">
</tr>
</table>
<table style="width:100%;" cellpadding="5" border-collapse="0">
<tr class="back">
<td colspan="6"><font color="white" >copyright 2022 All right reserved<br></font></td>
</tr>


</table>
</body>
</html>

**Comment by Manishhmakhija** [comment]
please assign me this issue @vikhyatsingh123
I can design an interactive contact us page.

**Comment by gamandeepsingh** [comment]
hey! Assign me for a responsive contact page

**Comment by draksham** [comment]
I have already created a Contact us page using React JS with the provide information of Name , E-mail , Message , submit button also the message will be sent to a users email i have used emailjs for this to send emails to other persons

**Comment by Manishhmakhija** [comment]
Can you plz accept my pull request I have to show some pull requests in
college as a contributor

**Comment by vikhyatsingh123** [comment]
If anyone completed it, then create PR
