### ISSUE TITLE
Wrong `line-height` in the `About` heading

### ISSUE THREAD

**Issue by beatrizsmerino** [vikhyatsingh123/Naruto-Shippuden#960]
I found a bug in the mobile version of the page about. The title text `This Project Is Developed by Vikhyat Singh` has a very small `line-height`.

![Mobile Title](https://user-images.githubusercontent.com/14045148/197645247-952229ac-6a9b-42f7-be03-df2df52fedde.png)

**Comment by beatrizsmerino** [comment]
@vikhyatsingh123 Can I help you with this?
I'm having a hard time finding a project to participate in for this year's `hacktoberfest`, if you could add the label it would help me a lot.

**Comment by vikhyatsingh123** [comment]
Sure, you can do it

**Comment by vikhyatsingh123** [comment]
Hacktoberfest label isn't needed. Once your pr merged, it will automatically count under Hacktoberfest

**Comment by beatrizsmerino** [comment]
> Sure, you can do it

It is solved in the Pull Request https://github.com/vikhyatsingh123/Naruto-Shippuden/issues/961

**Comment by beatrizsmerino** [comment]
> Hacktoberfest label isn't needed. Once your pr merged, it will automatically count under Hacktoberfest

If I think you may be right
![Hacktoberfest](https://user-images.githubusercontent.com/14045148/197709764-a0e72261-5be0-4cf5-abf0-155e208c3a01.png)
